version: '3.4'
 
services:
  frontend:
      build:
        context: ./
        dockerfile: ./docker/frontend/Dockerfile
      restart: always
      ports:
      - "4200"
      volumes:
        - ./frontend:/usr/src/app
        - /usr/src/app/node_modules
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev_data
  server:
      build:
        context: ./
        dockerfile: ./docker/server/Dockerfile
      restart: always
      depends_on:
        - postgres
      ports:
      - "5001:5001"
      volumes:
        - ./server:/usr/src/app
        - /usr/src/app/node_modules
  nginx:
    build: ./docker/nginx
    restart: always
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    links:
     - frontend
    depends_on:
      - frontend